name: jarvis_flutter
description: Interface Mobile do J.A.R.V.I.S. (Flutter)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  socket_io_client: ^2.0.3+1
  record: 5.1.0        # Versão específica estável
  audioplayers: ^5.2.1
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  google_fonts: ^6.1.0
  animate_do: ^3.3.4

dependency_overrides:
  # Força a interface a uma versão compatível para evitar o erro RecordLinux
  record_platform_interface: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
